version: '3.9'

services:
  python:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/project
    command: python app/main.py
    environment:
      PORT: '5000'
    depends_on:
      db:
        condition: service_healthy

  db:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
    image: mariadb:10.9
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uapp", "-papp" ]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  database:
    name: "monitoring-app-database"
