version: '3.9'

services:
  python:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/project
    command: python app/main.py
    environment:
      PORT: '5000'

  db:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
    image: mariadb:10.9
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
    name: "monitoring-app-database"
