name: Trigger Deploy on render.com

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: ${{ secrets.DEPLOY_HOOK }}
