# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Build .exe
      uses: Nuitka/Nuitka-Action@v0.4
      with:
        script-name: app/main.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe
        path: build/main.exe

