name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: release-${{ github.run_id }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifact for deployment jobs
        uses: actions/upload-release-asset@v2
        asset_name: monitoring
        with:
          name: python-app